name: NuxtJS site CI

on:
  push:
    branches: [ main ]
    paths:
      - 'nuxtjs-site/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd nuxtjs-site
          npm install
      - name: Build
        run: |
          cd nuxtjs-site
          npm run build
